kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
# - role: control-plane
#   image: kindest/node@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
containerdConfigPatches:
- |
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
    endpoint = ["https://hub.geekery.cn"]
