apiVersion: v1
kind: Secret
metadata:
  name: prometheus-sa-secret
  namespace: monitoring  # 替换为你的命名空间
  annotations:
    kubernetes.io/service-account.name: prometheus-sa
type: kubernetes.io/service-account-token