apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9091']
      
      # - job_name: 'mysql-exporter'
      #   static_configs:
      #     - targets: ['172.20.0.2:30104']
          
      - job_name: 'mysql-exporter'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: mysql
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: '9104'
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: instance
          

          
          

      