apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress
spec:
  mode: all
  selector:
    labelSelectors:
      app: mysql
  stressors:
    memory:
      workers: 4
      size: "256MB"
  duration: '300s'