apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
spec:
  action: pod-failure
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: mysql
  duration: '300s'