# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   labels:
#     app: mysql
# spec:
#   ports:
#   - name: mysql
#     port: 3306
#   clusterIP: None
#   selector:
#     app: mysql

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30007
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-metrics
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - port: 9104
    name: metrics
    nodePort: 30104  # 可选，指定外部访问的端口
  selector:
    app: mysql
---


# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the master: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql