apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
    bind-address = 0.0.0.0
    port = 3306
    innodb_buffer_pool_size = 3G
    innodb_log_file_size = 512M
    innodb_flush_log_at_trx_commit = 2
    slow_query_log = 1
    long_query_time = 2
    max_allowed_packet = 20971520
    wait_timeout = 864000
    interactive_timeout = 864000

  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
    bind-address = 0.0.0.0
    port = 3306
    innodb_buffer_pool_size = 3G
    innodb_log_file_size = 512M
    innodb_flush_log_at_trx_commit = 2
    slow_query_log = 1
    long_query_time = 2
    max_allowed_packet = 20971520
    wait_timeout = 864000
    interactive_timeout = 864000
    
  .my.cnf: |
    [client]
    user=root
    host=127.0.0.1
    port=3306